config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    Rails.application.routes.default_url_options[:host] = "localhost:3000"
  elsif Rails.env.production?
    Rails.application.routes.default_url_options[:host] = "revisionhub.uk"
  end

  devise_for :students, controllers: { registrations: 'registrations',
                                        passwords: 'passwords',
                                        confirmations: 'confirmations' }, path: '',
                        path_names: { sign_in: 'signin',
                                      sign_out: 'signout',
                                      sign_up: 'signup',
                                      password: 'forgot',
                                      confirmation: 'confirm' }

  get '/blog', to: 'pages#blog'
  get '/demo', to: 'pages#demo'
  get '/features', to: 'pages#features'
  get '/pricing', to: 'pages#pricing'

  resources :sessions

  scope module: 'tags' do
    resources :subject_tags, :topic_tags
  end

  devise_scope :student do
    match '/sessions/student', to: 'devise/sessions#create', via: :post
  end

  authenticated :student do
    root 'subjects#index', as: "authenticated_root"
  end

  root 'pages#home'

  resources :subjects do
    resources :topics
    resources :grades
  end
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :topic, optional: true
  belongs_to :subject
  belongs_to :student
  before_save :assign_student

  def assign_student
    self.student_id = self.subject.student.id
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  layout "form", only: [:edit, :new]

  before_action :authenticate_student!
  before_action :find_subject, only: [:index, :edit, :update, :new, :create, :destroy]
  before_action :find_grade, only: [:edit, :update, :destroy]
  before_action :find_topics, only: [:edit, :update, :new, :create]
  before_action :find_colours, only: [:edit, :update, :new, :create]

  before_action only: [:index, :update, :create, :destroy, :edit, :new] do |c|
    c.authenticate_subject_rights @subject
    c.authenticate_premium_student current_student
  end

  def index
    if current_student.grades.empty?
      redirect_to new_subject_grade_path
    else
      @grades = @subject.grades.order("date ASC, created_at DESC")
    end
  end

  def edit
  end

  def update
    if @grade.update(grade_params)
      redirect_to subject_grades_path(@subject), notice: "Grade successfully edited"
    else
      render 'edit'
    end
  end

  def new
    @grade = @subject.grades.build
  end

  def create
    @grade = @subject.grades.build(grade_params)

    if @grade.save
      redirect_to subject_grades_path(@subject), notice: "Grade successfully added"
    else
      render 'new'
    end
  end

  def destroy
    @grade.destroy
    redirect_to subject_grades_path(@subject), notice: "Grade successfully deleted"
  end

  private

  def grade_params
    params.require(:grade).permit(:grade, :percentage, :date, :topic_id, :colour)
  end

  def find_grade
    @grade = @subject.grades.find(params[:id])
  end

  def find_topics
    @topics = @subject.topics
  end

  def find_colours
    @colours = ["Green", "Orange", "Red"]
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.haml
= simple_form_for [@subject, @grade] do |f|
  .form-divider
    = f.input :grade
    = f.input :percentage
  .form-divider
    = f.label :date, class: "inline"
    = f.date_select :date, as: :date,
      discard_year: true,
      order: [:day, :month],
      label: false
  .form-divider
    = f.label :topic_id, class: "inline"
    = f.collection_select(:topic_id, @topics, :id, :name, include_blank: "No topic")
  .form-divider
    = f.label :colour, class: "inline"
    = f.collection_select(:colour, @colours, :to_s, :to_s)
  = f.button :submit

app/views/grades/edit.html.haml
- @title = "Edit grade"

%h1 Edit grade

= render 'form'

app/views/grades/index.html.haml
- @title = "Grades"

- unless @grades.blank?
  .grade-wrapper
    - @grades.each do |g|
      .grade
        %span{class: g.colour.camelize(:lower)}= g.grade
        %p= formatted_date(g)
        %ul.options
          %li= link_to "Edit", edit_subject_grade_path(g.subject, g)
          %li= link_to "Delete", subject_grade_path(g.subject, g), method: :delete, data: { confirm: "Are you sure?" }

app/views/grades/new.html.haml
- @title = "Add grade"

%h1 Add grade

= render 'form'