config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    Rails.application.routes.default_url_options[:host] = "localhost:3000"
  elsif Rails.env.production?
    Rails.application.routes.default_url_options[:host] = "revisionhub.uk"
  end

  devise_for :students, controllers: { registrations: 'registrations',
                                        passwords: 'passwords',
                                        confirmations: 'confirmations' }, path: '',
                        path_names: { sign_in: 'signin',
                                      sign_out: 'signout',
                                      sign_up: 'signup',
                                      password: 'forgot',
                                      confirmation: 'confirm' }

  get '/blog', to: 'pages#blog'
  get '/demo', to: 'pages#demo'
  get '/features', to: 'pages#features'
  get '/pricing', to: 'pages#pricing'

  resources :sessions

  scope module: 'tags' do
    resources :subject_tags, :topic_tags
  end

  devise_scope :student do
    match '/sessions/student', to: 'devise/sessions#create', via: :post
  end

  authenticated :student do
    root 'subjects#index', as: "authenticated_root"
  end

  root 'pages#home'

  resources :subjects do
    resources :topics
    resources :grades
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :student
  has_many :topics, dependent: :destroy
  has_many :grades
  has_and_belongs_to_many :subjectTags
  validates :name, length: { in: 2..60 },
                   presence: true,
                   uniqueness: { scope: "student_id" }
  validates :teacher, presence: true,
                      length: { in: 2..50 }

  default_scope -> { order("name ASC") }

  scope :tagfilter, ->(name) {
    joins(:subjectTags).where(subject_tags: { name: name }) if name.present?
  }

  def hyphenated_name
    words = self.name.downcase.split(" ")
    hyphenated = "#{words[0]}"
    words.drop(1).each do |word|
      hyphenated += "-#{word}"
    end

    return hyphenated
  end

  def no_sessions(range="all")
    i = 0
    topics.each do |topic|
      if range == "week"
        i += topic.sessions.where(date: Chronic.parse('monday', context: :past) .. Time.now).count
      elsif range == "all"
        i += topic.sessions.count
      end
    end

    return i
  end

  def session_duration_total(range="all")
    cumulative_total = 0

    topics.each do |topic|
      if range == "week"
        topic.sessions.where(date: Chronic.parse('monday', context: :past) .. Time.now).each do |session|
          cumulative_total += session.duration
        end
      elsif range == "all"
        topic.sessions.each do |session|
          cumulative_total += session.duration_hours
        end
      end
    end

    cumulative_minutes = cumulative_total % 60
    cumulative_hours = (cumulative_total - cumulative_minutes) / 60

    return [cumulative_hours, cumulative_minutes, cumulative_total]
  end

  def target_progress
    duration = self.session_duration_total('week')[2].to_f
    target_in_mins = (self.target.to_f * 60)

    return duration/target_in_mins
  end

  def target_amount_to_offset
    if self.target_progress > 1
      return 0
    else
      return (1 - self.target_progress) * 324.75
    end
  end

  def target_data
    return "#{(self.target_progress * 100).round(0)}%"
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout "form", only: [:edit, :new]

  before_action :authenticate_student!
  before_action :find_subject, only: [:show, :edit, :update, :destroy]
  before_action :find_subject_tags, only: [:edit, :update, :create, :new]
  before_action :find_filter, only: [:index, :show]

  before_action only: [:show, :update, :destroy, :edit] do |c|
    c.authenticate_subject_rights @subject
  end

  def index
    @subjects = current_student.subjects.tagfilter(@filter).order("name ASC")
    @target_classes = @subjects.map{|x| ".target.#{x.hyphenated_name}"}.join(", ")
    @name = current_student.first_name
    @subjects_with_targets = @subjects.where('target > ?', 0)

    if @subjects.blank?
      redirect_to new_subject_path
    end
  end

  def show
    @topics = @subject.topics.tagfilter(@filter).order("name ASC")
  end

  def edit
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: "Subject successfully edited"
    else
      render 'edit'
    end
  end

  def new
    @subject = current_student.subjects.build
  end

  def create
    @subject = current_student.subjects.build(subject_params)

    if @subject.save
      redirect_to @subject, notice: "Subject successfully created"
    else
      render 'new'
    end
  end

  def destroy
    @subject.destroy
    redirect_to root_path, notice: "Subject successfully deleted"
  end

  private

  def find_subject
    @subject = Subject.find(params[:id])
  end

  def find_subject_tags
    @subject_tags = current_student.subjectTags
  end

  def find_filter
    @filter = params[:filter] if params[:filter].present?
  end

  def subject_params
    params.require(:subject).permit(:name, :teacher, {subjectTag_ids: []}, :target)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def sessions_duration(subject)
    duration = formatted_duration(subject.session_duration_total('week'), conjunctive: true)
    return "#{duration} this week"
  end

  def time_of_day
    current_time = Time.now.to_i
    midnight = Time.now.beginning_of_day.to_i
    noon = Time.now.middle_of_day.to_i
    five_pm = Time.now.change(:hour => 17 ).to_i
    eight_pm = Time.now.change(:hour => 20 ).to_i

    if midnight.upto(noon).include?(current_time)
      return "morning"
    elsif noon.upto(five_pm).include?(current_time)
      return "afternoon"
    elsif five_pm.upto(midnight + 1.day).include?(current_time)
      return "evening"
    end
  end

  def greeting(name)
    return "Good #{time_of_day}, #{name}"
  end

  def statistic(student)
    duration =  formatted_duration(student.session_duration_total(range="week"), conjunctive: true)
    return "You have revised for #{duration} this week"
  end
end

app/views/subjects/_form.html.haml
= simple_form_for @subject do |f|
  = f.input :name, label: false, placeholder: "Subject name"
  = f.input :teacher, label: false, placeholder: "Teacher's name"
  = f.input :target, label: false, placeholder: "Target weekly hours"
  %h2 Subject tags
  = f.association :subjectTags, label: false, as: :check_boxes, collection: @subject_tags
  = link_to "Add subject tags", new_subject_tag_path, class: "form", target: :_blank
  = f.button :submit

app/views/subjects/edit.html.haml
- @title = "Edit #{ @subject.name }"

%h1= @subject.name.capitalize

= render 'form'

app/views/subjects/index.html.haml
- @title = "Dashboard"
- @page = "dashboard"

.top-section
  .top.initial-animate
    .greeting.left
      %h1= greeting(@name)
      %p= statistic(current_student)
    .right
      - if @filter.present?
        %p.filter Filtering by #{@filter}
        %ul.options
          %li= link_to "Clear filter", root_path
      - else
        %p.filter Not currently filtering
        %ul.options
          %li Click a tag to filter
  .targets
    - @subjects_with_targets.each do |subject|
      = render 'target', subject: subject

- unless @subjects.blank?
  - @subjects.each do |subject|
    .section-wrapper.dashboard-subject
      .left
        %a{href: subject_path(subject)}
          %p.important.name= subject.name.capitalize
        = render "tags", tags: subject.subjectTags, type: "subjectTags"
      .right
        %p= sessions_duration(subject)

app/views/subjects/new.html.haml
- @title = "New subject"
- @page = "new subject"

%h1 New subject

= render 'form'

app/views/subjects/show.html.haml
- @title = "#{ @subject.name.capitalize }"

.subject-wrapper
  .subject-section-wrapper
    .left
      %h1.name= @subject.name.capitalize
      = render "tags", tags: @subject.subjectTags, type: "subjectTags"
      %h3= @subject.teacher
    .right
      - if @filter.present?
        .filter
          %p Filtering by #{@filter}
      %ul.options
        - if @filter.present?
          %li= link_to "Clear filter", subject_path(@subject)
        %li= link_to "Edit", edit_subject_path
        %li= link_to "Add topic", new_subject_topic_path(@subject)
        - if current_student.premium?
          %li= link_to "Grades", subject_grades_path(@subject)
          %li= link_to "Add grade", new_subject_grade_path(@subject)
        %li= link_to "Delete", subject_path(@subject), method: :delete, data: { confirm: "Are you sure?" }
  - if @subject.topics.blank?
    .subject-section-wrapper
      %h3 It doesn't look like you've added any topics yet
  - else
    - @topics.each do |topic|
      .subject-section-wrapper
        .left
          %h2.name= topic.name.capitalize
          = render "tags", tags: topic.topicTags, type: "topicTags"
          %ul.options
            %li= link_to "Edit", edit_subject_topic_path(@subject, topic)
            %li= link_to "Delete", subject_topic_path(@subject, topic), method: :delete, data: { confirm: "Are you sure?" }
        .right
          .topic-data-wrapper
            %p Sessions revised:
            %span.topic-data= topic.sessions.count
          .topic-data-wrapper
            %p Percentage:
            %span.topic-data= topic.session_percentage