config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    Rails.application.routes.default_url_options[:host] = "localhost:3000"
  elsif Rails.env.production?
    Rails.application.routes.default_url_options[:host] = "revisionhub.uk"
  end

  devise_for :students, controllers: { registrations: 'registrations',
                                        passwords: 'passwords',
                                        confirmations: 'confirmations' }, path: '',
                        path_names: { sign_in: 'signin',
                                      sign_out: 'signout',
                                      sign_up: 'signup',
                                      password: 'forgot',
                                      confirmation: 'confirm' }

  get '/blog', to: 'pages#blog'
  get '/demo', to: 'pages#demo'
  get '/features', to: 'pages#features'
  get '/pricing', to: 'pages#pricing'

  resources :sessions

  scope module: 'tags' do
    resources :subject_tags, :topic_tags
  end

  devise_scope :student do
    match '/sessions/student', to: 'devise/sessions#create', via: :post
  end

  authenticated :student do
    root 'subjects#index', as: "authenticated_root"
  end

  root 'pages#home'

  resources :subjects do
    resources :topics
    resources :grades
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :redirect_to_https

  protected

  def authenticate_subject_rights(subject)
    authenticate_rights(subject, "Subject doesn't belong to you")
  end

  def authenticate_session_rights(session)
    authenticate_rights(session, "Session doesn't belong to you")
  end

  def authenticate_rights(model, message)
    unless model.student == current_student
      redirect_to root_path, alert: message
    end
  end

  def authenticate_premium_student(student)
    unless student.premium?
      redirect_to root_path, alert: "You need a premium account to do that"
    end
  end

  def find_subject
    @subject = Subject.find(params[:subject_id])
  end

  # def redirect_to_https
  #   redirect_to protocol: "https://" unless (request.ssl? || request.local?)
  # end
end

app/controllers/tags/application_controller.rb
class Tags::ApplicationController < ApplicationController
  layout "form", only: [:edit, :new]

  before_action :authenticate_student!
  before_action :find_tag_colours, only: :new

  protected

  def find_tag_colours
    @tag_colours = ["Blue", "Green", "Purple", "Red", "Yellow", "Orange"]
  end

  def tag_params(tagType)
    params.require(tagType).permit(:name, :colour)
  end

  def redirect_after_submission(tagVariable, successfulMessage)
    if tagVariable.save
      redirect_to root_path, notice: successfulMessage
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(d)
    d.strftime("%A %e %B %Y")
  end

  def nat_lang(n)
    if n == 1
      return "once"
    elsif n ==2
      return "twice"
    else
      return "#{n.to_words} times"
    end
  end

   def inline_svg(path)
     raw Rails.application.assets.find_asset(path + '.svg').to_s
   end

   def formatted_duration(duration, conjunctive=false)
     # duration[0] is the hours of the duration
     # duration[1] is the minutes of the duration

     if duration[0] > 0
       if duration[0] == 1
         hours = "1 hr"
       else
         hours = "#{duration[0]} hrs"
       end
     end

    if duration[1] > 0
      if duration[1] == 1
        # if there are hours and 1 minute
        minutes = "1 min"
      else
        # if there are hours and multiple minutes
        minutes = "#{duration[1]} mins"
      end
    elsif duration[1] == 0 && duration[0] <= 0
      # if there isn't any duration
      minutes = "0 mins"
    end

    if conjunctive && duration[0] > 0 && duration[1] > 0
      return "#{hours} and #{minutes}"
    elsif !conjunctive && duration[0] > 0 && duration[1] > 0
      return "#{hours}, #{minutes}"
    else
      return "#{hours} #{minutes}"
    end
  end
end

app/views/application/_analytics.html.haml
%script
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50410843-3', 'auto');
  ga('send', 'pageview');

app/views/application/_animations-css-and-js.html.erb
<script>
  $(document).on("turbolinks:before-cache", function() {
    $('<%= j @target_classes %>').removeClass('animated-target');
  });
  $(document).on("turbolinks:load", function() {
    $('<%= j @target_classes %>').addClass('animated-target');
  });
  $(document).on("turbolinks:render", function() {
    $('.top').removeClass('initial-animate');
  });
</script>

<style>
  <% subjects.each do |subject| %>
    .target.<%= subject.hyphenated_name %>.animated-target circle.ui-filled{
      stroke-dashoffset: <%= subject.target_amount_to_offset %>;
      animation: <%= "target-load-#{subject.hyphenated_name}" %> <%= (324.75 - subject.target_amount_to_offset)/162.325 %>s forwards linear;
    }

    @keyframes target-load-<%= subject.hyphenated_name %> {
      from {
        stroke-dashoffset: 400;
      }
      to {
        stroke-dashoffset: <%= subject.target_amount_to_offset %>;
      }
    }
  <% end %>
</style>

app/views/application/_footer.haml
- devise ||= false

%footer
  .footer-wrapper
    %a.logo{href: root_path, class: ("center" if devise)}
      = inline_svg('logo')
    %nav
      %ul
        %li= link_to "Support", root_path
        %li= link_to "Sign in", new_student_session_path
        %li= link_to "Sign up", new_student_registration_path

app/views/application/_head.html.haml
- if @title.blank?
  %title= "Revisionhub"
- else
  %title= "Revisionhub: " + @title
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags
%meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
%meta{name: "theme-color", content: "#242931"}
%link{rel: "canonical", href: "http://www.revisionhub.uk"}
%link{rel: "icon", href: "#{image_path("favicon.png")}"}

- if @page == "dashboard"
  = render 'animations-css-and-js', subjects: @subjects_with_targets

app/views/application/_nav-bar.html.haml
- devise ||= false

.nav-bar{class: [("home" if @page == "home"), ("clone" if clone == true)]}
  .wrapper
    %a.logo{href: root_path, class: ("center" if devise)}
      = inline_svg('logo')
    - unless devise
      %nav
        - if student_signed_in?
          %ul
            %li{class: ("current-page" if @page == "dashboard")}= link_to "Dashboard", root_path
            %li{class: ("current-page" if @page == "new subject")}= link_to "Add Subject", new_subject_path
            %li{class: ("current-page" if @page == "sessions")}= link_to "Sessions", sessions_path
            %li{class: ("current-page" if @page == "new session")}= link_to "Log a session", new_session_path
            %li= link_to "Sign out", destroy_student_session_path, method: :delete
        - elsif !student_signed_in?
          %ul.group1
            %li{class: ("current-page" if @page == "home")}= link_to "Home", root_path
            %li= link_to "Features", features_path
            %li= link_to "Pricing", pricing_path
            %li= link_to "Blog", blog_path
          %ul.group2
            %li= link_to "Support", root_path
            %li= link_to "Sign in", new_student_session_path
            %li= link_to "Sign up", new_student_registration_path

app/views/application/_notice_and_alert.html.haml
- if notice
  .notice-wrapper
    %p.notice= notice
- elsif alert
  .alert-wrapper
    %p.alert= alert

app/views/application/_tags.html.haml
- subject ||= @subject

- unless tags.empty?
  .tags
    - tags.order("name ASC").each do |t|
      - if type == "topicTags"
        = link_to t.name, subject_path(subject, filter: t.name), class: ["tag", t.colour]
      - elsif type == "subjectTags"
        = link_to t.name, root_path(filter: t.name), class: ["tag", t.colour]

app/views/application/_target.html.haml
.target{class: subject.hyphenated_name}
  %svg{:height => "180", :version => "1.1", :width => "180", :xmlns => "http://www.w3.org/2000/svg"}
    %circle{:cx => "90", :cy => "90", :fill => "none", :r => "69", :stroke => "#e1e1e1", "stroke-dasharray" => "324.75,649.5", "stroke-linecap" => "round", "stroke-width" => "20"}
    %circle.ui-filled{:cx => "90", :cy => "90", :fill => "none", :r => "69", "stroke-dasharray" => "324.75,649.5", "stroke-dashoffset" => "324.75", "stroke-linecap" => "round", "stroke-width" => "20.5"}
  .target-content
    %p.target-subject= subject.name
    %p.target-data= subject.target_data

app/views/application/_targets-css-and-js.html.erb
<script>
  $(document).on("turbolinks:before-cache", function() {
    <% subjects.each do |subject| %>
    $('<%= j ".target.#{subject.hyphenated_name}" %>').removeClass('animated-target');
    <% end %>
  });
  $(document).on("turbolinks:load", function() {
    <% subjects.each do |subject| %>
    $('<%= j ".target.#{subject.hyphenated_name}" %>').addClass('animated-target');
    <% end %>
  });
  $(document).on("turbolinks:render", function() {
    $('.top').removeClass('initial-animate');
  });
</script>

<style>
  <% subjects.each do |subject| %>
    .target.<%= subject.hyphenated_name %>.animated-target circle.ui-filled{
      stroke-dashoffset: 324.75;
      animation: <%= "target-load-#{subject.hyphenated_name}" %> 1s forwards linear;
    }

    @keyframes target-load-<%= subject.hyphenated_name %> {
      from {
        stroke-dashoffset: 400;
      }
      to {
        stroke-dashoffset: <%= subject.target_amount_to_offset * 324.75 %>;
      }
    }
  <% end %>
</style>

app/views/application/_targets-css.html.erb
<script>
  $(document).ready( function() {
    <% subjects.each do |subject| %>
        $('<%= j ".target.#{subject.hyphenated_name}" %>').addClass('animated-target');
    <% end %>
  });
</script>

<style>
  <% subjects.each do |subject| %>
    .target.<%= subject.hyphenated_name %>.animated-target circle.ui-filled{
      animation: <%= "target-load-#{subject.hyphenated_name}" %> 1s forwards linear;
    }

    @keyframes target-load-<%= subject.hyphenated_name %> {
      from {
        stroke-dashoffset: 400;
      }
      to {
        stroke-dashoffset: <%= subject.target_amount_to_offset * 324.75 %>;
      }
    }
  <% end %>
</style>